### ISSUE TITLE
Tree Builder deprecated

### ISSUE THREAD

**Issue by tfavareille** [sendinblue/APIv3-symfony-bundle#12]
Can you fix this depreciation ?

The "Symfony\Component\Config\Definition\Builder\TreeBuilder::root()" method called for the "sendinblue_api" configuration is deprecated since Symfony 4.3, pass the root name to the constructor instead.

**Comment by TorbenKoehn** [comment]
Hello, I've opened a PR for this (https://github.com/sendinblue/APIv3-symfony-bundle/pull/13) but it's not clear if this repository is still updated at all, so I wouldn't bet on it getting merged.

For now I'm using this in my `composer.json`:

```
   ...
    "repositories": [
        {
            "type": "vcs",
            "url": "git@github.com:TorbenKoehn/APIv3-symfony-bundle"
        }
    ],
    ...
    "require": {
        "sendinblue/api-bundle": "dev-master",
     }
```

which works fine (it contains the patch in my PR) and will let you upgrade to SF5 cleanly.

If there is enough interest I might think about taking over this bundle here, either with SIB's consent or without

**Comment by ekta-slit** [comment]
This package has been deprecated. As an alternative https://github.com/sendinblue/APIv3-php-library can be used to integrate Sendinblue APIs.
