### ISSUE TITLE
Can't install on OroCommerce

### ISSUE THREAD

**Issue by AdriwanKenoby** [sendinblue/APIv3-symfony-bundle#2]
I try to install this bundle on OroCommerce application, I have follow the instruction for single client but I have always `[RuntimeException]                                                                   
  [Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]        
    The child node "key" at path "sendinblue_api.clients.default" must be configured.`
when i try to clear cache
`php app/console cache:clear`

**Comment by MatTheCat** [comment]
Could you paste a sample of your configuration?

**Comment by AdriwanKenoby** [comment]
I just add this :
```
sendinblue_api:
        endpoints:
            - smtp
        key: xkeysib-********
 ```

to the parameters.yml file in app/config, but oro comes with a lot of configuration. 
Do you need I provide it ? Oro is based on symfony 2.8.

**Comment by MatTheCat** [comment]
You're missing the `sendinblue_api` node. Also you need to set `key` and `endpoints` as confguration values, not parameters.

**Comment by AdriwanKenoby** [comment]
Just a typo error, i had define `sendinblue_api:` but as parameters not as configuration value that was my mistake.
Thanks a lot for your great work
