### ISSUE TITLE
Add a transport for the Symfony mailer component

### ISSUE THREAD

**Issue by deguif** [sendinblue/APIv3-symfony-bundle#9]
Just to launch a topic about providing an official sendinblue transport for the Symfony mailer component which should be released very soon. 
Maybe this could be added on another repository.

**Comment by mykiwi** [comment]
Some resources:
- https://speakerdeck.com/fabpot/emails-reloaded
- https://github.com/symfony/symfony/tree/master/src/Symfony/Component/Mailer/Bridge

**Comment by erichard** [comment]
@MatTheCat Any news on this ?

**Comment by MatTheCat** [comment]
Nope, I left SendinBlue before this issue was open..!

**Comment by ekta-slit** [comment]
This package has been deprecated. As an alternative https://github.com/sendinblue/APIv3-php-library can be used to integrate Sendinblue APIs.
